// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210107145638_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.DatabaseModel.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Domain.DatabaseModel.DLC", b =>
                {
                    b.Property<Guid>("DLCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SteamAppID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DLCId");

                    b.ToTable("DLC");
                });

            modelBuilder.Entity("Domain.DatabaseModel.DealDate", b =>
                {
                    b.Property<Guid>("DealDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Expired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpiringDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LimitedTimeDeal")
                        .HasColumnType("bit");

                    b.HasKey("DealDateId");

                    b.ToTable("DealDate");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Developer", b =>
                {
                    b.Property<Guid>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("DeveloperId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Developer");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Game", b =>
                {
                    b.Property<Guid>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReleaseDateID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SteamAppId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.HasIndex("ReleaseDateID");

                    b.HasIndex("SteamAppId")
                        .IsUnique();

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameCategory", b =>
                {
                    b.Property<Guid>("GameCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameCategoryId");

                    b.ToTable("GameCategory");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameDLC", b =>
                {
                    b.Property<Guid>("GameDLCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DLCId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameDLCId");

                    b.ToTable("GameDLC");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameDeal", b =>
                {
                    b.Property<Guid>("GameDealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DealDateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PriceOverviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameDealId");

                    b.HasIndex("DealDateId");

                    b.HasIndex("PriceOverviewId");

                    b.HasIndex("StoreId");

                    b.ToTable("GameDeal");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameDeveloper", b =>
                {
                    b.Property<Guid>("GameDeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameDeveloperId");

                    b.ToTable("GameDeveloper");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameGenre", b =>
                {
                    b.Property<Guid>("GameGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameGenreId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GamePublisher", b =>
                {
                    b.Property<Guid>("GamePublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GamePublisherId");

                    b.ToTable("GamePublisher");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenreId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Platform", b =>
                {
                    b.Property<Guid>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlatformId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("Domain.DatabaseModel.PriceOverview", b =>
                {
                    b.Property<Guid>("PriceOverviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FinalPriceFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceOverviewId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("PriceOverview");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Publisher", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PublisherId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("Domain.DatabaseModel.ReleaseDate", b =>
                {
                    b.Property<Guid>("ReleaseDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ComingSoon")
                        .HasColumnType("bit");

                    b.Property<string>("ReleasedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReleaseDateId");

                    b.ToTable("ReleaseDate");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Screenshot", b =>
                {
                    b.Property<Guid>("ScreenshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PathFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathThumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScreenshotId");

                    b.ToTable("Screenshot");
                });

            modelBuilder.Entity("Domain.DatabaseModel.SteamApp", b =>
                {
                    b.Property<Guid>("SteamAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SteamId")
                        .HasColumnType("int");

                    b.Property<string>("SteamReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SteamReviewCount")
                        .HasColumnType("int");

                    b.HasKey("SteamAppId");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("SteamApp");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreId");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Domain.DatabaseModel.SystemRequirement", b =>
                {
                    b.Property<Guid>("SystemRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Minimum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recommended")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemRequirementId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SystemRequirement");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Video", b =>
                {
                    b.Property<Guid>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Highlight")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Domain.DatabaseModel.VideoContent", b =>
                {
                    b.Property<Guid>("VideoContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Max")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VideoContentId");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoContent");
                });

            modelBuilder.Entity("Domain.DatabaseModel.Game", b =>
                {
                    b.HasOne("Domain.DatabaseModel.ReleaseDate", "ReleaseDate")
                        .WithMany()
                        .HasForeignKey("ReleaseDateID");

                    b.HasOne("Domain.DatabaseModel.SteamApp", "SteamApp")
                        .WithMany()
                        .HasForeignKey("SteamAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseDate");

                    b.Navigation("SteamApp");
                });

            modelBuilder.Entity("Domain.DatabaseModel.GameDeal", b =>
                {
                    b.HasOne("Domain.DatabaseModel.DealDate", "DealDate")
                        .WithMany()
                        .HasForeignKey("DealDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DatabaseModel.PriceOverview", "PriceOverview")
                        .WithMany()
                        .HasForeignKey("PriceOverviewId");

                    b.HasOne("Domain.DatabaseModel.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DealDate");

                    b.Navigation("PriceOverview");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.DatabaseModel.PriceOverview", b =>
                {
                    b.HasOne("Domain.DatabaseModel.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Domain.DatabaseModel.SystemRequirement", b =>
                {
                    b.HasOne("Domain.DatabaseModel.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Domain.DatabaseModel.VideoContent", b =>
                {
                    b.HasOne("Domain.DatabaseModel.Video", null)
                        .WithMany("VideoContent")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DatabaseModel.Video", b =>
                {
                    b.Navigation("VideoContent");
                });
#pragma warning restore 612, 618
        }
    }
}
